config/routes.rb
Rails.application.routes.draw do


  resources :favorite_listings, only: [:create, :destroy]
  resources :credit_records, only: [:create ,:show]
  resources :user_credits, only: [:new, :index, :show]
  resources :pictures, only: [:destroy]
  resources :listings do 
    collection do
      post :import
      get :autocomplete, :owner, :fav # <= add this line
    end
  end
  
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  resources :users do 
    resources :reviews
    collection do
      get :credit
    end
  end

  post '/rate' => 'rater#create', :as => 'rate'
  post '/credits/checkout' => 'user_credits#create'
 
  root 'home#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	has_many :favorite_listings
	has_many :credit_records
	has_many :pictures, :dependent => :destroy
	searchkick autocomplete: ['city']
	paginates_per 10
	# attr_accessible :address, :latitude, :longitude
	geocoded_by :address
	# has_attached_file :image,
	# 	:styles => {
	#       :thumb => "100x100#",
	#       :small  => "150x150>",
	#       :medium => "200x200" }
	# validates_attachment :image,
 #                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
	reverse_geocoded_by :latitude, :longitude do |obj,results|
	  if geo = results.first
	  	obj.state 	=geo.state
	    obj.city    = geo.city
	    obj.postal_code = geo.postal_code
	    obj.country = geo.country
	  end
	end

	after_validation :reverse_geocode, :geocode, :if => :address_changed?

	
	enum property: { landed: 1, 'High Rise': 2, other: 3 }
	enum furnished: { fully: 1, partialy: 2, basic: 3 }
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]

  # GET /listings
  # GET /listings.json
  def index
    @credit = CreditRecord.new
    if params[:query].present?
      @listingss = Listing.search params[:query], fields: [:search_tags], where: {imove_in: params[:imove_in], price: {gte: params[:lower], lte: params[:higher]}}, order: {published_at: :desc,}
      @listings = Kaminari.paginate_array(@listingss).page(params[:listing]).per(10)
    else
      @listings = Listing.all.order("published_at DESC").page(params[:listing]).per(10)
    end
    @hash = Gmaps4rails.build_markers(@listings) do |listing, marker|
      marker.lat listing.latitude
      marker.lng listing.longitude
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @credit = CreditRecord.new
    @listing = Listing.find(params[:id])
    @listing.search_tags << 'room rent' << 'house rent'
    @hash = Gmaps4rails.build_markers(@listing) do |listing, marker|
      marker.lat listing.latitude
      marker.lng listing.longitude
    end
    @listings = Listing.where(city: @listing.city).order("price ASC").first(6)
    @listing.view += 1
    if current_user
      if @listing.user.id == current_user.id
        @listing.view -= 1
      end
    end
    @listing.save
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
    @geokey = ENV['GEOAPI']
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    @listing.published_at = DateTime.now
    respond_to do |format|
      if @listing.save
        if params[:images]
          @uploaded_images = params[:images]
          @uploaded_images.each { |image, object|
            @listing.pictures.create(image: object)
          }
        end
        @listing.search_tags << @listing.city << @listing.state << @listing.postal_code << @listing.country
        @listing.save
        flash[:notice] = "new listing"
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        @listing.search_tags= []
        @listing.search_tags << @listing.city << @listing.state << @listing.postal_code << @listing.country
        @listing.save
        if params[:images]
          @uploaded_images = params[:images]
          @uploaded_images.each { |image, object|
            @listing.pictures.create(image: object)
          }
        end
        if params[:delete_images]
          params[:delete_images].each { |id|
            Picture.find(id).destroy
          }
        end
        flash[:notice] = "update done"
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :js => "window.location='/listings/#{@listing.id}'" }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def autocomplete
    render json: Listing.search(params[:query], autocomplete: true, limit: 10).map(&:city)
  end

  def owner
    @listings = Listing.where(user_id: current_user.id).order("published_at DESC").page params[:listing]
    @hash = Gmaps4rails.build_markers(@listings) do |listing, marker|
      marker.lat listing.latitude
      marker.lng listing.longitude
    end
  end

  def fav
    @listings = current_user.favorite_listings.page params[:listing]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :desc, :price, :address, :latitude, :longitude, :token, :coin, :published_at, :images, :imove_in, :property, :furnished, :area, :parking, :bathroom, :bedroom, :hide)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_auto_bump.html.erb
<%= form_for(@credit, html: { class: "form-horizontal", role: "form", onsubmit: "return confirm('7 credit will deduct from your account for auto bump.');" }) do |f| %>
  <%= f.hidden_field :type , :value => 'token' %>
  <%= f.hidden_field :listing_id , :value => @listing.id %>
  <%= f.submit "Auto Bump 7 Days",  class: "btn btn-primary" %>
<% end %>

app/views/listings/_drop.html.erb
<script>
$(document).ready(function(){
  Dropzone.autoDiscover = false;
  var myDropzone = new Dropzone('#listing_form', {
    paramName: "[images]", // The name that will be used to transfer the file
    maxFilesize: 2, // MB
    previewsContainer: "#previews",
    addRemoveLinks: true,
    autoProcessQueue: false,
    clickable: "#clickzone",
    maxFiles: 10,
    parallelUploads: 10,
    uploadMultiple: true,
    dictDefaultMessage:'',
    removedfile: function(file) {
      var id = $(file.previewTemplate).attr('id');
      var x = document.getElementById("image");
      var text = document.createElement('div');
      text.innerHTML = '<input type="checkbox" name="delete_images[]" value='+id + ' checked />'
      x.appendChild(text);
      var previewElement;
      return (previewElement = file.previewElement) != null ? (previewElement.parentNode.removeChild(file.previewElement)) : (void 0);
    },
    init: function(){
        <% @listing.pictures.each do |image| %>
        var id = <%= image.id %>
          var mockFile = { size: <%= image.image.size %>, type: 'image/jpeg' };
          this.options.addedfile.call(this, mockFile);
          this.options.thumbnail.call(this, mockFile, "<%= image.image.url(:thumb) %>");
           $(".dz-preview:last-child").attr("id", id);
        <% end %>
    },
    accept: function(file, done) {
      if (file.name == "justinbieber.jpg") {
        done("Naha, you don't.");
      }
      else { done(); }
    },
  });
  $("form").on("submit", function (event) {
    if (myDropzone.getQueuedFiles().length > 0) {
      event.preventDefault();
      event.stopPropagation();
      myDropzone.processQueue();
    }
    else {
      // Upload anyway without files
      dropzone.uploadFiles([ ]);
    }
     // Tell Dropzone to process all queued files.
  });
  myDropzone.on("queuecomplete", function(file) {
    window.location.href = "/listings/owner";
  });
  
})
</script>

app/views/listings/_extra_listing.html.erb
<%= link_to listing do %>
  <div class="col s12 m6 ">
    <div class="card">
      <div class="card-image slider">
        <ul class="slides">
          <% listing.pictures.each do |image| %>
            <li>
              <%= image_tag image.image, class:'responsive-img' %>
            </li>
          <% end %>
        </ul>
        <span class="card-title"><%= listing.name %></span>
      </div>
      <div class="card-content">
        <p>RM<%= listing.price %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/listings/_feature_listing.html.erb
<% if user_signed_in? %>
  <% if current_user.favorite_listing? @listing.id %>
    <%= form_tag("/favorite_listings/#{@listing.id}", class: "unlike-listing", remote: true, method: :delete) do %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <button class="empty-btn fav "><i class="fa fa-3x fa-heart "></i> </button>
    <% end %>
    <%= form_tag("/favorite_listing", class: "like-listing hide", remote: true,  method: :post) do %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= hidden_field_tag 'listing_id', @listing.id %>
      <button class="empty-btn fav "><i class="fa fa-3x fa-heart-o "></i> </button>
    <% end %>
  <% else %>
    <%= form_tag("/favorite_listings/#{@listing.id}", class: "unlike-listing hide", remote: true,  method: :delete) do %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <button class="empty-btn fav "><i class="fa fa-3x fa-heart "></i> </button>
    <% end %>
    <%= form_tag("/favorite_listings", class: "like-listing", remote: true, method: :post) do %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= hidden_field_tag 'listing_id', @listing.id %>
      <button class="empty-btn fav "><i class="fa fa-3x fa-heart-o "></i> </button>
    <% end %>
  <% end %>
<% end %>

app/views/listings/_form.html.erb
<div class="row listing-new">
<%= form_for(@listing, html: { class: "form-horizontal dropzone", multipart: true,  role: "form", id:"listing_form" }) do |f| %>
  <% if @listing.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <h5>Property</h5>
    <div class="input-field col s12">
      <%= f.label :name, class: "active" %>
      <%= f.text_field :name, class: "validate" %>
    </div>

    <div class="input-field col s12">
      <%= f.label :desc, class: "active" %>
      <%= f.text_field :desc, class: "validate" %>
    </div>
    <h5>Price</h5>
    <div class="input-field col s12">
      <%= f.label :price %>
      <div id="listing"></div>
      <%= f.number_field :price, class: "validate col s12 number-input", value: 600 %>
    </div>


      <p>
        <%= f.check_box :imove_in %>
        <label for="listing_imove_in">Instant Move In</label>
      </p>

    
    <h5>Location</h5>
    <p>
      <%= f.check_box :hide %>
      <label for="listing_hide">Hide Address</label>
    </p>
    <div class="input-field col s12">
      <label class="active" for="special">address</label>
      <%= f.hidden_field :latitude, id: "latitude" %>
      <%= f.hidden_field :longitude, id: "longitude" %>
      <%= hidden_field_tag 'city', request.location.city %>
      <%= f.text_field :address, class: "validate", id: "special", placeholder: "#{request.location.city}"%>
    </div>
    <div class="col s12">
      <div style='width: 90%;'>
      <div id="map" style='width: 90%; height: 400px;'></div>
      </div>
    </div>

    <h5>Information</h5>
    <div class="input-field col s12">
      <%= f.label :bedroom, class: "active" %>
      <%= f.text_field :bedroom, class: "validate" %>
    </div>

    <div class="input-field col s12">
      <%= f.label :bathroom, class: "active" %>
      <%= f.text_field :bathroom, class: "validate" %>
    </div>

    <div class="input-field col s12">
      <%= f.label :car_park, class: "active" %>
      <%= f.text_field :parking, class: "validate" %>
    </div>

    <div class="input-field col s12">
      <%= f.label :area, class: "active" %>
      <%= f.text_field :area, class: "validate" %>
    </div>
    
    <div class="input-field col s12">
      <%= f.label :furnished, class: "active" %>
      <%= f.select(:furnished, Listing.furnisheds.keys) %>
    </div>

    <div class="input-field col s12">
      <%= f.label :property, class: "active" %>
      <%= f.select(:property, Listing.properties.keys)  %>
    </div>  

    <div id="image"></div>

    


    <div class="col s12">
      <div class="card-panel waves-effect waves-block waves-green" id="clickzone">
          <span class="">Drop file here or click here
          </span>
        </div>
      <div classs="dropzone-previews" id ="previews"></div>
    </div>
    
  <div class="col s12">
    <div class="col-sm-offset-2 col-sm-10">
      <% if current_user.confirmed? %>
        <%= f.submit class: "btn btn-primary" %>
      <% else %>
        <%= link_to "Resend confirm email", new_confirmation_path(current_user), class: "btn btn-primary" %>
      <% end %>
    </div>
  
<% end %>
</div>
<script>
  var listingSlider = document.getElementById('listing');
  var value = document.getElementById('listing_price').value;

  noUiSlider.create(listingSlider, {
    start: [ value ],
    range: {
      'min': 500,
      'max': 2500
    },
    margin: 50,
    step: 50
  });

  var price = document.getElementById('listing_price');

  listingSlider.noUiSlider.on('update', function( values, handle ) {

    var value = values[handle];
      price.value = Math.round(value);
  });
</script>

<%= render 'drop' %>

app/views/listings/_geo_complete.html.erb
<!-- Geocomplete plugin -->
<script src="//cdn.jsdelivr.net/jquery.geocomplete/1.6.4/jquery.geocomplete.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GEOAPI'] %>&libraries=places"></script>

app/views/listings/_listing_filter.html.erb
<%= form_tag listings_path, method: :get do %>
  <div class="col-md-12">
    <div class="form-group">
      <%= text_field_tag :query, params[:query], class: 'form-control city', placeholder: "Where you want to rent?",  autocomplete: "off" %>
      <%= select_tag :imove_in, "<option value=false>Normal Move In</option><option value=true>Instant Move In</option>".html_safe %>
      
      <%= submit_tag 'Get your room now!', class: 'btn btn-info' %>
    </div>
  </div>
<% end %>

app/views/listings/_search_form.html.erb
<%= form_tag listings_path, method: :get do %>
    <div class="input-field">
      <div class="row ">
        <div class="col s2 l2 padding-zero">
          <%= button_tag(type: "submit", class: "waves-effect waves-light") do %>
            <i class="material-icons md-24">search</i>
          <% end %>
        </div>
        <div class="col s10 l4 padding-zero">
          <%= text_field_tag :query, params[:query], class: 'city home-form', placeholder: "Where you want to rent?",  autocomplete: "off" %>
        </div>
        <div class="col s12 l6 padding-zero">
          <a class='dropdown-button-listing waves-effect waves-light btn' href='#' data-activates='dropdown1'>
            <div><span class='text-left'>Filter</span><span class='text-right'>▼</span></div>
          </a>
        </div>
      </div>
    </div>
    <div id="dropdown1" class='row dropdown-content'>
      <div class="input-field col s6">
        <div class='move_in normal'>
           <%= radio_button_tag 'imove_in', false %>
          Normal move in
        </div>
      </div>
      <div class="input-field col s6">
        <div class='move_in instant'>
          <%= radio_button_tag 'imove_in', true %>
          Instat move in
        </div>
        
      </div>
      <div class="input-field col s12 left-align dark-grey-text b500">
        PRICE RANGE:
        <div id="html5"></div>
        <div class="col s5">RM
          <input type="number" class="number-input" name="lower" min="500" max="2500" step="1" id="lower">
        </div>
        <div class="col s2"></div>
        <div class="col s5">RM
          <input type="number" class="number-input" name="higher" min="500" max="2500" step="1" id="higher">
        </div>
      </div>
      <div class="input-field col s12">
        <%= button_tag(type: "submit", class: "waves-effect waves-light") do %>
          <i class="material-icons md-24">search</i>
        <% end %>
      </div>
    </div>
    
<% end %>
<script>
function getAllUrlParams(url) {

  // get query string from url (optional) or window
  var queryString = url ? url.split('?')[1] : window.location.search.slice(1);

  // we'll store the parameters here
  var obj = {};

  // if query string exists
  if (queryString) {

    // stuff after # is not part of query string, so get rid of it
    queryString = queryString.split('#')[0];

    // split our query string into its component parts
    var arr = queryString.split('&');

    for (var i=0; i<arr.length; i++) {
      // separate the keys and the values
      var a = arr[i].split('=');

      // in case params look like: list[]=thing1&list[]=thing2
      var paramNum = undefined;
      var paramName = a[0].replace(/\[\d*\]/, function(v) {
        paramNum = v.slice(1,-1);
        return '';
      });

      // set parameter value (use 'true' if empty)
      var paramValue = typeof(a[1])==='undefined' ? true : a[1];

      // (optional) keep case consistent
      paramName = paramName.toLowerCase();
      paramValue = paramValue.toLowerCase();

      // if parameter name already exists
      if (obj[paramName]) {
        // convert value to array (if still string)
        if (typeof obj[paramName] === 'string') {
          obj[paramName] = [obj[paramName]];
        }
        // if no array index number specified...
        if (typeof paramNum === 'undefined') {
          // put the value on the end of the array
          obj[paramName].push(paramValue);
        }
        // if array index number specified...
        else {
          // put the value at that index number
          obj[paramName][paramNum] = paramValue;
        }
      }
      // if param name doesn't exist yet, set it
      else {
        obj[paramName] = paramValue;
      }
    }
  }

  return obj;
}
var i_move = getAllUrlParams().imove_in;
if (i_move == "true") {
  $('.instant').toggleClass('hli');
    var Id = $('.instant').find('input[type=radio]').attr('id');
} else {
  $('.normal').toggleClass('hli');
    var Id = $('.normal').find('input[type=radio]').attr('id');
}
document.getElementById(Id).click();
  $('.dropdown-button-listing').dropdown({
    constrain_width: false,
    hover:true
    }
  );
  $('.move_in').click(function () {
    $('.hli').toggleClass('hli');
    $(this).toggleClass('hli');
    var Id = $(this).find('input[type=radio]').attr('id');
    document.getElementById(Id).click();
  });
  $(".dropdown-content").click(function(e){
    e.stopPropagation();
  });
  $('.dropdown-content').on('touchstart click', function (e) {
    e.stopPropagation();
  });
</script>

app/views/listings/_show_item.html.erb
<div class="row">
  <div class="col s12">
    <h1><%= @listing.name %></h1>
    <p><i><%= @listing.city %></i></p>
  </div>
  <div class="col s12 desc">
    <%= @listing.desc %>
  </div>
  <div class="col s12">
    <h6 >Tel: <%= @listing.user.contact %> </h6>
  </div>
  <div class="col s12">
    <h6 ><%= "Instant Move In" if @listing.imove_in %> </h6>
  </div>
  <div class="col s12 price">
    <span>RM<%= @listing.price %></span> per month
  </div>
  <div class="col s3"><i class="fa fa-bed dark-green-text" aria-hidden="true"></i></div>
  <div class="col s1">:</div>
  <div class="col s8"><%= @listing.bedroom %></div>
  <div class="col s3"><i class="fa fa-shower dark-green-text" aria-hidden="true"></i></div>
  <div class="col s1">:</div>
  <div class="col s8"><%= @listing.bathroom %></div>
  <div class="col s3"><i class="fa fa-car dark-green-text" aria-hidden="true"></i></div>
  <div class="col s1">:</div>
  <div class="col s8"><%= @listing.parking %></div>
  <div class="col s3">Area</div>
  <div class="col s1">:</div>
  <div class="col s8"><%= @listing.area %> sqft</div>
  <div class="col s3">Furnished</div>
  <div class="col s1">:</div>
  <div class="col s8"><%= @listing.furnished.capitalize %></div>
  <div class="col s3">Type</div>
  <div class="col s1">:</div>
  <div class="col s8"><%= @listing.property.capitalize %></div>

  <div class="col s3 owner">
    <i class="fa fa-user dark-green-text" aria-hidden="true"></i> Owner
  </div>
  <div class="col s1 owner">:</div>
  <div class="col s8 owner">
    <%= link_to @listing.user.name, user_path(@listing.user_id) %>
  </div>
  
  <% unless @listing.hide %>
    <div class="col s3 owner">
      <i class="fa fa-map-marker red-text" aria-hidden="true"></i> Address
    </div>
    <div class="col s1 owner">:</div>
    <div class="col s8 owner">
      <%= @listing.address %>
    </div>
  <% end %>

</div>

app/views/listings/fav.js.erb
$('#listing-item').append('<%= escape_javascript render partial: 'fav_item', collection: @listings.page(params[:listing]), as: :listing, :window => 2%>');
$('.slider').slider({height: 200, interval: 3000, indicators: false});
<% if @listings.next_page %>
  $('#listing-num').append('<%= escape_javascript(paginate(@listings.page(params[:listing]), :remote => true, param_name: 'listing').to_s) %>');
<% else %>
  $(window).off('scroll');
  $('#listing-num').html('No More Rooms');
<% end %>

app/views/listings/index.html.erb
<%= render 'google_map_script' %>
<div class="page-header">
  <div class="inline-block left">
    <%= render 'search_form' %>
  </div> 
  <div class="result inline-block">
    <span><%= params[:query] %></span> 
    <span class="grey-text total"><i> <%= @listings.total_count %> results</i></span>
  </div>
  <div class="inline-block right">
  <%= link_to new_listing_path, class: 'btn-floating btn-large waves-effect waves-light','data-no-turbolink' => true do %>
    <i class="material-icons">add</i>
  <% end %>
  </div>
</div>
<div class="row">
  <div class="col hidden-xs hide fixed-map">
    <div style='width: 100%;'>
    <div id="map" style='width: 90%; height: 400px;'></div>
    </div>
  </div>
  <div class="col s12">
    <div id="listing-item">
      <span class="infinite-item">
        <%= render partial: 'item', collection: @listings.page(params[:listing]), as: :listing %>
      </span>
    </div>
    <div id="listing-num" >
      <%= paginate @listings.page(params[:listing]), :remote => true, param_name: 'listing' %>
    </div>
  </div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>
<%= render 'home/slider' %>

app/views/listings/new.html.erb
<%= render 'geo_complete' %>
<div class="page-header">
  <%= link_to listings_path, class: 'btn btn-default', 'data-no-turbolink' => true do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New listing</h1>
</div>

<%= render 'form' %>
<script type="text/javascript">
$("#special").geocomplete({
  map: "#map",
  mapOptions: {
    zoom: 6,
    scrollwheel: true
  },
  location: "<%= current_user.stage %>",
  markerOptions: {
    draggable: true
  },
  details: "#special"
});
$("#special").bind("geocode:dragged", function(event, latLng){
  $("#latitude").val(latLng.lat());
  $("#longitude").val(latLng.lng());
});
</script>

app/views/listings/owner.js.erb
$('#listing-item').append('<%= escape_javascript render :partial => "listings/item", collection: @listings.page(params[:listing]), as: :listing, :window => 2%>');
$('.slider').slider({height: 200, interval: 3000, indicators: false});
<% if @listings.next_page %>
  $('#listing-num').html('<%= escape_javascript(paginate(@listings.page(params[:listing]), :remote => true, param_name: 'listing').to_s) %>');
<% else %>
  $(window).off('scroll');
  $('#listing-num').html('No More Rooms');
<% end %>

app/views/listings/show.html.erb
<%= content_for :title do %>
  <%= "#{@listing.name}" %>
<% end %>

<%= content_for :head do %>
  <% meta_tag :title, @listing.name %>
  <% meta_tag :description, @listing.desc.first(150)+'...' %>
  <% meta_tag :keywords, @listing.search_tags.join(',') %>
  <%= render partial: 'facebook_og', locals: {listing: @listing} %>
  <link rel="canonical" href="<%= request.path %>">
  <meta property="fb:article_style" content="default">
<% end %>
<div class="page-header-listing">
  <%= link_to listings_path, class: 'left', 'data-no-turbolink' => true  do %>
    <i class=" fa fa-3x fa-chevron-left" aria-hidden="true"></i>
  <% end %>
  <%= link_to edit_listing_path(@listing), class: 'right', 'data-no-turbolink' => true  do %>
    <h4>Edit</h4>
    
  <% end %>
  Share<%= render 'share' %>
</div>
<div class="listing-show">
  <div class="row">
    <div class="col l5">
      <%= image_tag @listing.pictures[0].image.url, class:'responsive-img' %>

      <%= render_gallery_for @listing.pictures %>
      <br>
      <%= render 'feature_listing' %>
      <% if current_user.present? && current_user.id == @listing.user_id %>
        <%= render 'auto_bump' %>
        <%= render 'highlight' %>
        <%= render 'bump' %>
        <% if @listing.published_at > 1.day.ago %>
          <p>About <%= ((@listing.published_at + 1.day - Time.now )/3600).round %> hour to bump again<p>
        <%end%>
      <% end %>
      <div class="row">
        <%= render  partial: 'extra_listing', collection: @listings, as: :listing %>
      </div>
    </div>
    <div class="col l7">
      <%= render 'show_item' %>
    </div>
    <div class="col l5">
    </div>
    <div class="col l7">
      <div style='width: 100%;'>
        <div id="map" style='width: 90%; height: 482px;'></div>
      </div>
    </div>
    
  </div>
</div>
<%= render 'google_map_script' %>
<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(15);
  });
</script>