config/routes.rb
Rails.application.routes.draw do


  resources :favorite_listings, only: [:create, :destroy]
  resources :credit_records, only: [:create ,:show]
  resources :user_credits, only: [:new, :index, :show]
  resources :pictures, only: [:destroy]
  resources :listings do 
    collection do
      post :import
      get :autocomplete, :owner, :fav # <= add this line
    end
  end
  
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  resources :users do 
    resources :reviews
    collection do
      get :credit
    end
  end

  post '/rate' => 'rater#create', :as => 'rate'
  post '/credits/checkout' => 'user_credits#create'
 
  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :confirmable, :rememberable, :trackable, :validatable
	has_many :lisitngs
  has_many :credit_records
  has_many :favorite_listings
  has_many :raters, through: :reviews, class_name: "User", foreign_key: :user_id # The users this user has rated
  has_many :users, through: :reviews, class_name: "User", foreign_key: :reter_id
  has_many :user_credits
  has_attached_file :image,
    :styles => {
      :thumb => "60x60#",
      :medium => "200x200#"
  }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/x
	def has_payment_info?
	  braintree_customer_id
	end

  def favorite_listing? listing
    return true unless self.favorite_listings.where(listing_id: listing).empty?
    return false
  end

  def code_generate
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    self.code = (0...8).map { o[rand(o.length)] }.join
  end

  protected
  def confirmation_required?
    false
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  private

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def sign_up_params
    params.require(:user).permit(:name, :email, :identity_card, :stage, :image, :password, :password_confirmation, :contact)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :identity_card, :stage, :image, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @review = Review.new
    @reviews = Review.where(user_id:params[:id])
    @user_credit = UserCredit.where(user_id: current_user)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def credit
    @user = current_user
    @credits = current_user.credit_records.order('created_at DESC')
    @braintree_token = generate_client_token
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def generate_client_token
      if current_user.has_payment_info?
        Braintree::ClientToken.generate(customer_id: current_user.braintree_customer_id)
      else
        Braintree::ClientToken.generate
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :identity_card, :stage, :image, :contact)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col s12 l4 user">
    <% unless current_user.image.url.empty? %>
      <%= image_tag current_user.image.url, id: 'img_prev', class:'circle ' %>
    <% else %>
      <img id="img_prev" class="hidden" src="#" alt="your image" />
    <% end %>
    <div class="row">
      <div class="input-field file-field col s12">
        <div class="btn">
          <span>File</span>
          <%= f.file_field :image, onchange: "readURL(this);" %>
        </div>
      </div>
    </div>
  </div>

  <div class="col s12 l8">
    <div class="row">
      <div class="input-field col s12 l8">
        <%= f.label :name, class: "active" %>
        <%= f.text_field :name, class: "validate" %>
      </div>
      <div class="input-field col s12 l8">
        <%= f.label :email, class: "active" %>
        <%= f.text_field :email, class: "validate" %>
      </div>
      
      <div class="input-field col s12 l8">
        <%= f.label :contact, class: "active" %>
        <%= f.text_field :contact, class: "validate" %>
      </div>
      <div class="input-field col s12 l8">
        <%= f.label :identity_card, class: "active" %>
        <%= f.text_field :identity_card, class: "validate" %>
      </div>
      <div class="input-field col s12 l8">
        <%= f.label :stage, class: "active" %>
        <%= f.text_field :stage, class: "validate" %>
      </div>

      <div class="input-field col s12 bottom">
        <%= f.submit 'Update Details', class: "btn waves-effect waves-light" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_payment.html.erb
<form id="checkout" method="post" action="/credits/checkout">
  <div class="modal-content">
    <h4 class="modal-title">Topup Credit</h4>
    <div class="value">
    </div>
    <div id="payment-form" class='hide'>
    </div>
    <div class="submit-btn hide">
      <input type="submit" class= "btn waves-effect waves-green btn-info" value="Pay">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Cancel</a>       
    </div>
    <div class="row" id="payment">
      <div class="col s12 l4">
        <div class="radio">
          <input name="user_credit[amount]" id="user_creditcredit1" type="radio" class='with-gap' value='20'/>
          <label for="user_creditcredit1">
            <div class="payment-header">Newbie choice</div>
            <div class="payment-get">Get </div>
            <div class="payment-price">30</div>
            <div class="payment-credit">credits</div>
            <div class="payment-desc">for only </div>
            <span class ="btn user_creditcredit1">RM20</span>
          </label>
        </div>
      </div>
      <div class="col s12 l4">
        <div class="radio">
          <input name="user_credit[amount]" id="user_creditcredit2" type="radio" class='with-gap' value='50'  />
          <label for="user_creditcredit2">
            <div class="payment-header">Popular choice</div>
            <div class="payment-get">Get </div>
            <div class="payment-price">70</div>
            <div class="payment-credit">credits</div>
            <div class="payment-desc">for only </div>
            <span class ="btn user_creditcredit2">RM20</span>
          </label>
        </div>
      </div>
      <div class="col s12 l4">
        <div class="radio">
          <input name="user_credit[amount]" id="user_creditcredit3" type="radio" class='with-gap' value='80'/>
          <label for="user_creditcredit3">
            <div class="payment-header">Exclusive choice</div>
            <div class="payment-get">Get </div>
            <div class="payment-price">90</div>
            <div class="payment-credit">credits</div>
            <div class="payment-desc">for only </div>
            <span class ="btn user_creditcredit3">RM80</span>
          </label>
        </div>
      </div>
    </div>
  </div>
  
</form>
<script src="https://js.braintreegateway.com/js/braintree-2.23.0.min.js"></script>
<script>
var clientToken = "<%= @braintree_token%>";

braintree.setup(clientToken, "dropin", {
  container: "payment-form"
});
</script>

app/views/users/_payment__history.html.erb
<div class="card-panel teal black-text padding-bottom2rem <%= credit_counter%2 != 1 ? 'white-text' : 'lighten-4 black-text' %>">
  <%= link_to credit_record_path(credit.id, :format => :pdf) do %>
  <div class="col s12 m4">
    Purchase Time: <%= credit.created_at.localtime.strftime("%Y-%m-%d %I:%M %p") %>
  </div>
  <div class="col s12 m4">
    Type: <%= credit.item.capitalize %>
  </div>
  <div class="col s12 m4">
    <div class="row">
      <div class="col s6">
        Balance Credit: <%= credit.balance %>
      </div>
      <div class="col s6">
        Credit Before: <%= credit.credit %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/_purchase_history.html.erb
<div class="card-panel teal black-text padding-bottom2rem <%= purchase_counter%2 != 1 ? 'white-text' : 'lighten-4 black-text' %>">
  <%= link_to user_credit_path(purchase.id, :format => :pdf) do %>
  <div class="col s12 m2">
    Invoice: <%= purchase.id %>
  </div>
  <div class="col s12 m2">
    Amount: RM <%= purchase.amount %>
  </div>
  <div class="col s12 m2">
    Credit: <%= purchase.credits %>
  </div>
  <div class="col s12 m4">
    Purchase Time: <%= purchase.created_at.localtime.strftime("%Y-%m-%d %I:%M %p") %>
  </div>
  <% end %>
</div>

app/views/users/credit.html.erb
<div class="page-header">
  <%= link_to users_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_user_path(@user), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Payment & transcation</h1>
  <div class="card-panel  red lighten-5 ">
    Credit Balance: <%= current_user.credit %>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s4"><a href="#payment">Payment</a></li>
      <li class="tab col s4"><a href="#payments">Payment History</a></li>
      <li class="tab col s4"><a href="#purchases">Purchase History</a></li>
    </ul>
  </div>
  <div id="payment" class="col s12">
    <%= render 'payment' %>
  </div>
  <div id="payments" class="col s12">
      <%= render partial: 'payment__history', collection: @credits, as: :credit  %>
  </div>
  <div id="purchases" class="col s12">
    <%= render partial: 'purchase_history', collection: @user.user_credits.order('created_at DESC'), as: :purchase %>
  </div>
  
</div>

app/views/users/edit.html.erb
<div class="page-header user">
  <h1>Profile Detail</h1>
</div>
<div class="row">
  <%= render 'form' %>
</div>
<div class="user">
  <h2>Password</h2>
</div>
<div class="row">
  <%= link_to 'change password', edit_user_registration_path, class: 'btn waves-effect waves-light red' %>
</div>


<%= link_to users_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
<% end %>
<%= link_to @user, class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-info-sign"></span>
  Show
<% end %>

app/views/users/index.html.erb
<div class="page-header">
  <%= link_to new_user_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New User
  <% end %>
  <h1>Listing users</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Identity card</th>
            <th>Stage</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @users) do |user| %>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.identity_card %></td>
            <td><%= user.stage %></td>
            <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="page-header">
  <%= link_to users_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New user</h1>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <%= link_to users_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_user_path(@user), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show user</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @user.name %></dd>

  <dt>Email:</dt>
  <dd><%= @user.email %></dd>

  <dt>Image:</dt>
  <dd> <%= image_tag @user.image.url(:medium) %></dd>
  <dt>Identity card:</dt>
  <dd><%= @user.identity_card %></dd>

  <dt>Stage:</dt>
  <dd><%= @user.stage %></dd>
  <% if @reviews %>
    <% @reviews.each do |review| %>
      <dt>Review:</dt>
      <dd><%= review.comment %></dd>
      <dt>Rate By:</dt>
      <dd><%= review.rater.name %></dd>
      <div class="star-rating" data-score=<%= review.rating %>></div>
    <% end %>
  <% end %>
</dl>

<div class="row">
  <div class="col-md-6">
    <%= form_for([@user,@review], html: { class: "form-horizontal", role: "form" }) do |f| %>
      <% if @review.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>

          <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :comment, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :comment, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :rating, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
           <div id="star"></div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
    <% @user_credit.each do |x| %>
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>Amount</th>
              <th>Purchase Date</th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <th><%= x.amount %></th>
              <th><%= x.created_at.to_time.strftime('%e %B %Y at %l:%M %p') %></th>
            </tr>
          </tbody>
        </table>
      </div>
    <% end %>
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#topup">Topup Credit</button>
  <!-- Modal -->
    <div class="modal fade" id="topup" role="dialog">
      <div class="modal-dialog">     
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Topup Credit</h4>
          </div>
          <div class="modal-body">
            <form id="checkout" method="post" action="/credits/checkout">
            <div id="payment-form">
              <div class="field">
                <label for="user_creditcredit">Credit Purchase</label> <br>
                <input type= "number" name="user_credit[credits]"> 
              </div>        
            </div>
            <div class="modal-footer">
              <input type="submit" class= "btn btn-info" value="Pay">
          
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>           
            </div>
            </form>
          </div>       
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>
<script>
  $('#star').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>