config/routes.rb
Rails.application.routes.draw do


  resources :favorite_listings, only: [:create, :destroy]
  resources :credit_records, only: [:create ,:show]
  resources :user_credits, only: [:new, :index, :show]
  resources :pictures, only: [:destroy]
  resources :listings do 
    collection do
      post :import
      get :autocomplete, :owner, :fav # <= add this line
    end
  end
  
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  resources :users do 
    resources :reviews
    collection do
      get :credit
    end
  end

  post '/rate' => 'rater#create', :as => 'rate'
  post '/credits/checkout' => 'user_credits#create'
 
  root 'home#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.rater_id = current_user.id
    @review.user_id = User.find(params[:user_id]).id
    respond_to do |format|
      if @review.save
        format.html { redirect_to root_path, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:user_id, :rater_id, :comment, :rating)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @review.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rater_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :rater_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :comment, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :comment, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rating, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :rating, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<div class="page-header">
  <%= link_to reviews_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @review, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing review</h1>
</div>

<%= render 'form' %>

app/views/reviews/index.html.erb
<div class="page-header">
  <%= link_to new_review_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Review
  <% end %>
  <h1>Listing reviews</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>User</th>
            <th>Rater</th>
            <th>Comment</th>
            <th>Rating</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @reviews) do |review| %>
            <td><%= review.user_id %></td>
            <td><%= review.rater_id %></td>
            <td><%= review.comment %></td>
            <td><%= review.rating %></td>
            <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reviews/new.html.erb
<div class="page-header">
  <%= link_to reviews_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New review</h1>
</div>

<%= render 'form' %>

app/views/reviews/show.html.erb
<div class="page-header">
  <%= link_to reviews_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_review_path(@review), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show review</h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @review.user_id %></dd>

  <dt>Rater:</dt>
  <dd><%= @review.rater_id %></dd>

  <dt>Comment:</dt>
  <dd><%= @review.comment %></dd>

  <dt>Rating:</dt>
  <dd><%= @review.rating %></dd>

</dl>