config/routes.rb
Rails.application.routes.draw do


  resources :favorite_listings, only: [:create, :destroy]
  resources :credit_records, only: [:create ,:show]
  resources :user_credits, only: [:new, :index, :show]
  resources :pictures, only: [:destroy]
  resources :listings do 
    collection do
      post :import
      get :autocomplete, :owner, :fav # <= add this line
    end
  end
  
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  resources :users do 
    resources :reviews
    collection do
      get :credit
    end
  end

  post '/rate' => 'rater#create', :as => 'rate'
  post '/credits/checkout' => 'user_credits#create'
 
  root 'home#index'

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row social-media-icon">
      <%= link_to '', 'www.google.com', class: 'mdi mdi-facebook mdi-18px circle-border' %>
      <%= link_to '', 'www.google.com', class: 'mdi mdi-instagram mdi-18px circle-border' %>
      <%= link_to '', 'www.google.com', class: 'mdi mdi-twitter mdi-18px circle-border' %>
      <%= link_to '', 'www.google.com', class: 'mdi mdi-pinterest mdi-18px circle-border' %>
    </div>
    <div class="row user-link">
      <ul>
        <li><a href="#modal1" class="modal-trigger">Payment</a></li>
        <li><%= link_to 'listings', listings_path,'data-no-turbolink' => true %></li>
        <li><%= link_to 'lisitng', 'www.google.com' %></li>
        <li><%= link_to 'lisitng', 'www.google.com' %></li>
      </ul>
    </div>
    <div class="row normal-link">
      <ul>
        <li><%= link_to 'lisitng', 'www.google.com' %></li>
        <li><%= link_to 'lisitng', 'www.google.com' %></li>
        <li><%= link_to 'lisitng', 'www.google.com' %></li>
        <li><%= link_to 'lisitng', 'www.google.com' %></li>
      </ul>
    </div>
    <div class="row address">
      address of office
    </div>
    <div class="row copyright">
      Copyright @xxx All right reserved. <spam class='primary-text'>A product of xxx</span>
    </div>
  </div>
</div>

app/views/layouts/_menu_block.html.erb
<%= link_to current_user.name, edit_user_path(current_user.id) %>
<% if current_user.credit == 0 || current_user.nil? %>
  <%= link_to credit_users_path do %>
    <b>Top Up</b>
  <% end %>
<% else %>
  <%= link_to credit_users_path do %>
    <div class="dark-green-text"><b>Credit: <%= current_user.credit %></b></div>
    
  <% end %>
<% end %>

app/views/layouts/_nav_bar.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to "Money", root_path, class: "left brand-logo margin-left2rem" %>
    <a href="#" data-activates="mobile-demo" class="right button-collapse show-on-large margin-right2rem"><i class="material-icons">menu</i></a>

    <ul class="side-nav" id="mobile-demo">
      <% if user_signed_in? %>
        <li>
          <%= render 'layouts/user_info' %>
        </li>
        <li><%= link_to 'Listing', owner_listings_path, 'data-no-turbolink' => true %></li>
        <li><%= link_to 'Favorite', fav_listings_path %></li>
        <li><%= link_to 'Payment', credit_users_path, 'data-no-turbolink' => true %></li>
        <li><%= link_to 'Profile', edit_user_path(current_user.id) %></li>
        <li><a href="#!">Close</a></li>
        <li class='menu-li'><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_user_info.html.erb
<div class="card-panel grey lighten-5 z-depth-1">
  <div class="row">
    <div class="col s12">
      <%= image_tag current_user.image.url, class:'circle responsive-img margin-top1rem' %>
    </div>
    <div class="col s12">
      <span class="black-text">
        <%= render 'layouts/menu_block' %>
      </span>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      <%= t('meta_tags.title.home') %>
    <% end %>
  </title>
  <meta name='description'
      content='<%= yield_meta_tag(:description) %>' />
  <meta name='keywords'
    content='<%= yield_meta_tag(:keywords) %>' />
  <meta name='title'
    content='<%= yield_meta_tag(:title) %>' />
  <div id="fb-root"></div>
    <%= render :partial => 'analytics/facebook_sdk' %>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//cdn.materialdesignicons.com/1.7.22/css/materialdesignicons.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/nav_bar' %>
<%= render partial: "layouts/payment_form" %>
  <div class="container first-body">
    <% flash.each do |name, msg| %>
      <script>
        $(function() {
          Materialize.toast('<%= msg %>'+'<span><i class="material-icons">clear</i></span>' , 3000);
        });
        $(document).on('click', '#toast-container .toast', function() {
            $(this).fadeOut(function(){
                $(this).remove();
            });
        });
      </script>
    <% end %>

    <%= yield %>
  </div>
  <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/layouts/show.html.erb
<html>
  <head>   
    <%= wicked_pdf_stylesheet_link_tag  "application", :media => "all" -%>
  </head>
  <body>
    <%= yield %>
  </body>
</html>